include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_relative_imports
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - cancel_subscriptions
