name: obs_state_mixin

description: "Lightweight Flutter package for reactive state management using Obs and ObsStateMixin."

version: 0.0.1-dev.2

homepage: https://github.com/albinpk/obs_state_mixin/tree/dev/packages/obs_state_mixin
repository: https://github.com/albinpk/obs_state_mixin/tree/dev/packages/obs_state_mixin
issue_tracker: https://github.com/albinpk/obs_state_mixin/issues

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - observable
  - reactive
  - state-management
  - obs
  - state-mixin
